### PR TITLE
Use Astropy APE14 WCS

### PR DESCRIPTION
**Pull request by pllim**
This will be necessary if you ever want to visualize ASDF or ASDF-in-FITS, but not if you only care about FITS WCS. Do you need this, @Skyhawk172 , @mperrin ?

### CODE REVIEW

**Comment by Skyhawk172** [comment]
Do you know if DMS will ever produce ASDF files as part of the WFSC calibration pipeline? As far as I know, we'll be getting only FITS files. If that's the case, then I don't think we'd need it.

**Comment by mperrin** [comment]
I think not but let’s ask Marcio to find out for sure?

**Comment by mperrin** [comment]
Actually never mind. I’m sure the Ball WAS will never handle ASDF, so there must be some requirement we only get FITS and never ASDF for the WFSC data.

**Comment by pllim** [comment]
Not even ASDF-in-FITS? Just wanna make sure, but so far sounds like I can just close this without merge.

**Comment by pllim** [comment]
Closing then, not needed.

**Pull request closed without merging**
