### PR TITLE
Change min SBR for Pupil Imaging and CP to 1500

### PR DESCRIPTION
**Pull request by nflagey-stsci**
### Description

This pull request is to update min SBR values in SNRCalc.py for Pupil Imaging and Coarse Phasing (now at 1500 according to Scott Acton)

### CODE REVIEW

**Comment by pllim** [comment]
Thanks! Do you have a new table so we can make sure the documentation at https://wss-tools.readthedocs.io/en/latest/wss_tools/quip/snrcalc.html reflects what is actually happening?

**Comment by nflagey-stsci** [comment]
The only thing I have is an email from Scott Acton at Ball:

> Nick,
>  
> Focus Sweep, Segment ID, Image Array 1, GA1, IS1, Coarse MIMF (for forming the array), IA2, GA2, IS2 (for making the initial move) are 500.
>  
> Pupil Imaging, CP (1,2,3), coarse MIMF (for making field dependent measurements), IS2 (for the weak lens images), Fine Phasing (1,2,3), MF monitor, PSF focus check, MIMF images are all 1500.
>  
> Hope this is useful.
>  
> Scott

We cannot disentangle between different parts of an activity, so we'll have to add notes to our procedures for that.

**Comment by obi-wan76** [comment]
The original table is in Document No. D36168 Ball No. 2299462 Rev C, Table 3.  This document is ITAR but we could update the current table in the help with the new values. Where is the table in the documentation?

**Comment by pllim** [comment]
It is a image file (probably a screenshot from back in the days): https://github.com/spacetelescope/wss_tools/blob/master/docs/wss_tools/quip/images/sbr_limits_20150519.png

Feel free to remove it and replace with a nice Sphinx RST table. Please only include non-ITAR information.

**Comment by nflagey-stsci** [comment]
adding a new table to the Docs and changed the RST file so it points to the right PNG file

**Comment by pllim** [comment]
Can you please delete the old file (`sbr_limits_20150519.png`) too? Thanks!

**Comment by pllim** [comment]
p.s. The new PNG is a bit low resolution (at least for me) and hard to read, but as long as you can read it, it is fine by me.

**Review by obi-wan76 — APPROVED** [review]

**Review by pllim — APPROVED** [review]

**Comment by pllim** [comment]
Thanks!

**Pull request merged**
